# -*- coding: utf-8 -*-
"""backwardDeletion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y9JpoO7k4DsbyunBtExrJRzXNGNPNLPs
"""

from numpy.ma.core import remainder
import numpy as np
import pandas as pd 
import matplotlib as plt
import statsmodels.api as sm
db=pd.read_csv("50_Startups.csv")
x=db.iloc[:,:-1].values
y=db.iloc[:,-1].values
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
en=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
x=np.array(en.fit_transform(x))
x = np.append(arr = np.ones((50, 1)).astype(int), values = x, axis = 1)
x_opt=x[:,[0,1,2,3,4,5]]
x_opt = x_opt.astype(np.float64)
regressor_OLS = sm.OLS(endog = y, exog = x_opt).fit()
x_opt=x[:,[0,1,2,3,4]]
x_opt = x_opt.astype(np.float64)
regressor_OLS = sm.OLS(endog = y, exog = x_opt).fit()

x_opt=x[:,[0,1,2,3]]
x_opt = x_opt.astype(np.float64)
regressor_OLS = sm.OLS(endog = y, exog = x_opt).fit()
print(regressor_OLS.summary())