# -*- coding: utf-8 -*-
"""LRpractice3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ozeFn2URV9P3C37rzN-lfmu7dw0Gh3Es
"""



"""**simple Linear Regression**

**Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""**Import Dataset**"""

db=pd.read_csv("weight-height.csv")
x=db.iloc[:,:-1].values
y=db.iloc[:,-1].values

print(x)

print(y)

"""**Encoding Independent varaibles**"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

en=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder="passthrough")
x=en.fit_transform(x)

print(x)

"""**Split the dataset into training and test sets**"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x[:,2:],y,test_size=0.2,random_state=1)

"""Training the Linear Regression Model"""

from sklearn.linear_model import LinearRegression
regression=LinearRegression()
regression.fit(x_train,y_train)

"""**visualizing trainset results**"""

plt.scatter(x_train,y_train,color='red')
plt.plot(x_train,regression.predict(x_train),color="blue")
plt.title("height-weight")
plt.xlabel("height")
plt.ylabel("weight")
plt.show()

"""**Visualizing test results**"""

plt.scatter(x_test,y_test,color='red')
plt.plot(x_train,regression.predict(x_train),color="blue")
plt.title("height-weight")
plt.xlabel("height")
plt.ylabel("weight")
plt.show()