# -*- coding: utf-8 -*-
"""DTR1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mRCId5cZilpQsysZrdznrkrOown3uCX3

# Decision Tree Regression

## Importing the libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""## Importing the dataset"""

df=pd.read_csv("Position_Salaries.csv")
x=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values

"""## Training the Decision Tree Regression model on the whole dataset"""

from sklearn.tree import DecisionTreeRegressor
Regressor=DecisionTreeRegressor(random_state=0)
Regressor.fit(x,y)

"""## Predicting a new result"""

Regressor.predict([[6.5]])

"""## Visualising the Decision Tree Regression results (higher resolution)"""

x_grid=np.arange(min(x),max(x),step=0.1)
x_grid=x_grid.reshape(len(x_grid),1)
plt.scatter(x,y,color='red')
plt.plot(x_grid,Regressor.predict(x_grid),color='blue')
plt.title("Position-salaries(Decision Tree Regression")
plt.xlabel("Position")
plt.ylabel("salaries")
